#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X XI XII XIII XIV XV XVI XVII XVIII XIX

feh --bg-fill [insert your image file here]

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a [insert your web browser here] desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
# delete this if you are not xfce4-panel
bspc rule -a xfce4-panel layer=below sticky=off \
             manage=on focus=off border=off \
             locked=on
#insert your panel here
